name: iOS CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  list_xcode_versions:
    runs-on: macos-latest
    steps:
    - name: List installed Xcode versions
      run: ls /Applications | grep Xcode

